### ISSUE TITLE
Recruit at least one new member to participate in the Technical Working Group

### ISSUE THREAD

**Issue by brylie** [maas-alliance/community#1]
We have acknowledged that our working group is small and not fully representative of the diverse needs of the MaaS community. In order to represent stakeholders from various organizations, we have agreed to increase our outreach/recruitment activities.

# Task
- recruit at least one new member for the technical working group

This task can be marked as complete if/when the new working group member attends their first working group meeting (in-person or online)

**Comment by IRUProjects** [comment]
Perhaps https://free2move.com/ ? They integrate several car sharing systems and would for sure be interested to simplify the integrations by having a common API ...

**Comment by evermassen** [comment]
Since the start of the workgroup the number of attendants grew cosistently so this issue can be closed for now.
